### ISSUE TITLE
Lesson Objectives

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#107]
Lesson Objectives the tagline is:
By the end of this lesson, you should be able to:

And for the session Intro and Objectives it reads:
By the end of this session, you should: 

Just noting this so that we can check that we are consistent throughout

**Comment by castl350** [comment]
Thanks. i think we are pretty consistent on that because the activities were mostly pulled from old toddler, where we consistently use the "you should be able to" for the lessons. If you see any specific one that don't follow it, please note...the session ones should just say "you should" because the you should be able did not make sense with all objectives listed below.
