### ISSUE TITLE
S6 A2 All About Behavior Guidance

### ISSUE THREAD

**Issue by bnkerr** [castl350/Toddler#159]
Image on lesson objectives page is from PC video. 
Bold the word 'Know'

Interactive after Part 3 alignment issue with item "The children show ..."
Interactive after Part 4 alignment issue with item "When the children are being ..."

PART 4:
No video 
![5](https://cloud.githubusercontent.com/assets/19825728/16863759/1786f67e-4a24-11e6-924e-e1c1a6289387.jpg)

**Comment by castl350** [comment]
All of the images and wording is fixed. I'm leaving this open because the videos still have the CASTL Watermark in addition to the placeholder chart above and missing video etc.

![screen shot 2016-07-22 at 1 45 27 pm](https://cloud.githubusercontent.com/assets/3357288/17066145/acde9d2c-5013-11e6-9754-312506b1322e.png)

**Comment by castl350** [comment]
have matt looking at the watermark issue and the weird code jumping up before video loads.

**Comment by mattsema** [comment]
fixed skin
