### ISSUE TITLE
PRACTICE: Capturing Your Classroom Interactions

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#201]
The last sentence of the first paragraph should read:
For this recording, your interactions should focus on Emotional and Behavioral Support.

The second paragraph is not accurate ... 
The first two sentences should go in the Session 1 PRACTICE: Capturing Your Classroom Interactions
It starts with "Remember ..." and ends with "... out now."

Then the rest of it should read:
To review the steps for taping your classroom with the ipad, please locate the printed directions under the Technology tab in your notebook.
(Brittany please confirm)

**Comment by castl350** [comment]
Hi Allison, little confused by these directions because there is no session 1 practice? And, also i'm confused about how this homework is really playing. Maybe we should talk about this at our thursday meeting to make sure that this will feel easy for teachers?

Int terms of the directions, i've updated what i can, but i also was clear in the last testing round that I did not want to use the word "tab" in a web content because my first reaction was that there was  technology tab on some type navigation here..so i updated it to technology section in your notebook......

**Comment by ajp9e** [comment]
There is practice for Session 1 - they have to answer questions and try to videotape. The goal between kickoff and first conference is that teachers complete sessions 1 and 2 and videotape one time. So we thought that having a space for the information about videotaping should be in session 1. Teachers may tape after session 1 or session 2 because they just have to capture something … Perhaps it is best to briefly cover this on Thursday and finalize with Jennifer.

And I totally agree with whatever wording makes sense re: where to find the tech info.
