### ISSUE TITLE
S2 A4 Interactive question after Part 1

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#89]
The answer to this question is set up with the answer 'All of the above' - this question is on shuffle so the 'All of the Above' answer moves around.
So I suggest we change this to which of the following is NOT true about the TTIF and change the All of the Above choice to read 'A checklist for analyzing classrooms.'
Also the item that reads 'Will guide ...' needs to be revised to make more sense with the question prompt: "A guide to the way we look at, talk about, and analyze classroom interactions."

Also the correct/incorrect features for this doesn't work - if you chose the correct answer it gives you feedback; if you chose incorrectly it goes to Part 2

**Comment by castl350** [comment]
Hey allison, i'm not sure that "checklist of analyzing classrooms" would be enough for me to gauge because i'm not sure we emphasize the idea that's it's not a checklist? How about this for the wrong/right answer. This dialogue comes more from the script because i know we specifically say "it's important to know that the TTIF does not capture everything that happens in early childhood classrooms?"

Wrong/Correct answer: A comprehensive checklist that captures everything happening in early childhood classrooms.

With the following feedback:
That's right. Although the Teaching Through Interactions Framework captures a lot of the interactions that happen in an early childhood classroom, it is not a comprehensive checklist and does not capture everything. It is, however, designed to help us categorize and identify effective teacher-child interactions, as well as guide our own interactions in the classroom.

**Comment by castl350** [comment]
The flow of the activity has been fixed.

**Comment by castl350** [comment]
I checked this CYK and closed it for now. If the new option does not work it will get picked up in final testing.
