### ISSUE TITLE
S2 A4 End of the lesson

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#92]
The review option doesn't work - starts the lesson over instead of in review mode

**Comment by bnkerr** [comment]
And there's no "continue to next..." option. 

Scoring is off here too but maybe because it's not forcing us to keep trying until we get it right (see Allison's previous comment about this activity). 
![s2a4part4](https://cloud.githubusercontent.com/assets/19825728/16029270/8c1a440a-31b5-11e6-9e87-f513dcea14bf.jpg)

**Comment by castl350** [comment]
The review option does work :). It simply takes learners back to the start of the lesson. This is how the LMS works. The activity was not linked to a next lesson. I fixed this. The activity was not set to allow learners to try again. This is fixed.
