### ISSUE TITLE
S2 TYK

### ISSUE THREAD

**Issue by ajp9e** [castl350/Toddler#98]

**Comment by bnkerr** [comment]
T/F questions feedback don't tell if it's correct or incorrect like the others do. It's just marked in green or red.

**Comment by castl350** [comment]
Matt, can you check this one?

**Comment by castl350** [comment]
It appears to be a difference is wording as seen in the screenshot.  For a multiple choice question the system states if you are correct/incorrect then repeats the correct answer.  For a true/false question the system only repeats the correct answer.  This seems like expected behavior for this type of question?
![screen shot 2016-06-14 at 12 14 45 pm](https://cloud.githubusercontent.com/assets/3357288/16050519/f624fa92-3229-11e6-8a76-7611550980c2.png)

**Comment by castl350** [comment]
Looks like a function of LMS. Closing for now until further notice.
